language: java

os:
  - linux

jdk:
  - oraclejdk8

branches:
  only:
    - master


install:
  - mvn clean install -Dmaven.test.skip=true


script:
  - mvn test

deploy:
  - test $TRAVIS_TEST_RESULT || echo "TRAVIS_TEST_RESULT=$TRAVIS_TEST_RESULT no deployment"
  - test $TRAVIS_TEST_RESULT && mvn --settings settings.xml -Dmaven.test.skip=true deploy
