language: java

notifications:
  email:
      recipients:
        - tmjee1@gmail.com
      on_success: change
      on_failure: always

os:
  - linux

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /v.*/

install:
  - mvn clean install -DskipTests=true


script:
  - mvn clean install


after_failure:
  - printf "\n\n\n" \
    && printf "====================" \
    && printf "\n\tTRAVIS_TEST_RESULT=$TRAVIS_TEST_RESULT no deployment\n" \
    && printf "=====================" \
    && printf "\n\n\n"

after_success:
  - mvn clean install jacoco:report cobertura:cobertura coveralls:report
  - test $TRAVIS_TAG \
    && printf "\n\n\n" \
    && printf "==================" \
    && printf "\n\tThis is a tagged build $TRAVIS_TAG , Deployment will happen\n" \
    && printf "==================" \
    && printf "\n\n\n" \
    && mvn -X --settings settings.xml -Dmaven.test.skip=true deploy
  - test $TRAVIS_TAG \
    || printf "\n\n\n" \
    && printf "====================" \
    && printf "\n\tThis is NOT a tagged build, no deployment is going to happen\n" \
    && printf "====================" \
    && printf "\n\n\n"

