language: java

os:
  - linux

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_install:
  - pip install codecov

install:
  - mvn clean install -Dmaven.test.skip=true

after_install:
  - codecov

script:
  - mvn test


after_failure:
  - echo "TRAVIS_TEST_RESULT=$TRAVIS_TEST_RESULT no deployment"

after_success:
  - mvn --settings settings.xml -Dmaven.test.skip=true deploy
