language: java

notifications:
  email:
      recipients:
        - tmjee1@gmail.com
      on_success: change
      on_failure: always

os:
  - linux

jdk:
  - oraclejdk8

branches:
  only:
    - master

install:
  - mvn clean install -DskipTests=true


script:
  - mvn clean install


after_failure:
  - echo "TRAVIS_TEST_RESULT=$TRAVIS_TEST_RESULT no deployment"

after_success:
  - mvn clean install jacoco:report cobertura:cobertura coveralls:report
  - mvn --settings settings.xml -Dmaven.test.skip=true deploy

